{% set name = "ipasuite" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/Sargueil-CiTCoM/ipasuite

build:
  number: 0
  script: 
    - "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."
    # - "{{ PYTHON }} setup.py install" # --single-version-externally-managed --record=record.txt || exit 1; "
  
requirements:
  host:
    - python
    - pip
    - gcc 
    - setuptools
  run:
    - python=3.9
    - ipywidgets
    - ipyfilechooser
    - scipy
    - fire
    - parse
    - pandas
    - numpy=1.23
    - matplotlib
    - scikit-bio
    - snakemake
    - wheel
    - cython
    - jupyterlab
    - voila
    - ruamel.yaml
    - sip
    - ipanemap>=0.1.8
    - varna
    - colorlog
    
about:
  home: https://github.com/Sargueil-CiTCoM/ipasuite
  license: GPL3
  license_family: GPL3
  summary: 
