# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.


report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
container: "docker://continuumio/miniconda3"

include: "rules/common.smk"
include: "rules/tools.smk"
include: "rules/other.smk"
include: "rules/ipanemap.smk"
include: "rules/importation.smk"
rule all:
    input:
        #get_final_outputs()
        #get_all_raw_outputs()
        #get_all_qushape_outputs()
        #get_all_reactivity_outputs()
        #get_all_aggreact_outputs()
        #get_all_structure_outputs
        aggregates = get_all_aggreact_outputs(),
        #structures = get_all_structure_outputs
        vienna = get_all_vienna_outputs
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.

